# Generated by Django 3.1.4 on 2020-12-08 08:39

import api.models.depute
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depute',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('idAN', models.CharField(max_length=64)),
                ('slug', models.CharField(max_length=256)),
                ('fullName', models.CharField(max_length=256)),
                ('firstName', models.CharField(max_length=256)),
                ('lastName', models.CharField(max_length=256)),
                ('birthDate', models.DateField()),
                ('birthPlace', models.CharField(max_length=256, null=True)),
                ('departmentNumber', models.CharField(max_length=3)),
                ('districtName', models.CharField(max_length=256)),
                ('districtNumber', models.IntegerField()),
                ('dateMandateStart', models.DateField()),
                ('job', models.CharField(max_length=256, null=True)),
                ('chamberPlace', models.CharField(default='', max_length=4)),
                ('twitter', models.CharField(default='', max_length=124)),
                ('numberOfMandates', models.IntegerField(default=1)),
                ('otherMandates', models.JSONField(default=api.models.depute.array_default, verbose_name='other_mandates')),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=524)),
                ('acronym', models.CharField(max_length=8)),
                ('activeGroup', models.BooleanField()),
                ('rgbColor', models.CharField(max_length=12)),
            ],
        ),
    ]
