# Generated by Django 3.1.4 on 2020-12-08 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Synthese',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('amendmentAdopted', models.IntegerField()),
                ('amendmentProposed', models.IntegerField()),
                ('amendmentSigned', models.IntegerField()),
                ('commissionIntervention', models.IntegerField()),
                ('commissionAttendance', models.IntegerField()),
                ('hemicycleLongIntervention', models.IntegerField()),
                ('hemicycleShortIntervention', models.IntegerField()),
                ('propositionSigned', models.IntegerField()),
                ('propositionWritten', models.IntegerField()),
                ('questionWritten', models.IntegerField()),
                ('questionOral', models.IntegerField()),
                ('report', models.IntegerField()),
                ('weekAttendance', models.IntegerField()),
                ('date', models.CharField(max_length=124)),
                ('depute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.depute')),
            ],
        ),
    ]
